# User Configuration

#OE_TERMINAL = "tmux"

# Enable authenticated boot image generation
BOOTGEN_EXTRA_ARGS += " -secure"

# Use RSA authentication
IMAGE_FSTYPES += "wic"

# Enable FIT image signing support
UBOOT_SIGN_ENABLE = "1"

# Enable secure boot support
SECURE_BOOT = "1"

IMAGE_INSTALL:append = " mydriver"

EXTRA_IMAGE_FEATURES += "debug-tweaks"

IMAGE_BOOT_FILES:zynq = "BOOT.BIN image.ub boot.scr"